from enum import Enum


class QualificationStatus(Enum):
    FULLY_QUALIFIED = "FULLY_QUALIFIED"
    EDGE_ONLY = "EDGE_ONLY"
    HISTORY_ONLY = "HISTORY_ONLY"
    NEGATIVE_EV = "NEGATIVE_EV"
    INJURY_CONCERN = "INJURY_CONCERN"
    VALIDATION_FAILED = "VALIDATION_FAILED"
    NOT_QUALIFIED = "NOT_QUALIFIED"


class GameConstants:
    EDGE_THRESHOLDS = {
        "NBA": 8.0,
        "CBB": 8.0,
        "NFL": 3.5,
        "CFB": 3.5,
        "NHL": 0.5
    }

    MIN_GAMES = {
        "NBA": 20,
        "CBB": 15,
        "NFL": 6,
        "CFB": 6,
        "NHL": 15
    }
    MIN_GAMES_DEFAULT = 5

    MIN_GAMES_PLAYED = {
        "NBA": 5,
        "CBB": 15,
        "NFL": 3,
        "CFB": 3,
        "NHL": 5
    }

    SUPERMAX_EDGE = 12.0
    HIGH_EDGE = 10.0
    MEDIUM_EDGE = 8.0

    HISTORY_QUALIFY_RATE = 0.60
    SUPERMAX_HISTORY_RATE = 0.70
    HIGH_HISTORY_RATE = 0.65

    RETRY_MAX_ATTEMPTS = 3
    RETRY_BASE_DELAY = 0.3
    RETRY_BACKOFF_MULTIPLIER = 2

    API_TIMEOUT_DEFAULT = 15
    API_TIMEOUT_SCOREBOARD = 30
    API_TIMEOUT_LONG = 60

    CACHE_TTL_LIVE_SCORES = 15
    CACHE_TTL_TEAM_STATS = 3600
    CACHE_TTL_HISTORICAL = 43200
    CACHE_TTL_INJURY = 21600
    CACHE_TTL_SCHEDULE = 43200
    CACHE_TTL_OPENING_LINE = 86400

    RATE_LIMIT_ESPN = 5
    RATE_LIMIT_ODDS_API = 2

    CACHE_SIZE_DEFAULT = 500
    CACHE_SIZE_INJURY = 200
    CACHE_SIZE_LEAGUE_INJURY = 50


THRESHOLDS = GameConstants.EDGE_THRESHOLDS
